In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib as mpl
%matplotlib inline
# https://machinelearningmastery.com/feature-selection-machine-learning-python/

In [2]:
train = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')
train.head()

   id  label                                              tweet
0   1      0   @user when a father is dysfunctional and is s...
1   2      0  @user @user thanks for #lyft credit i can't us...
2   3      0                                bihday your majesty
3   4      0  #model   i love u take with u all the time in ...
4   5      0             factsguide: society now    #motivation

In [3]:
test.head()

      id                                              tweet
0  31963  #studiolife #aislife #requires #passion #dedic...
1  31964   @user #white #supremacists want everyone to s...
2  31965  safe ways to heal your #acne!!    #altwaystohe...
3  31966  is the hp and the cursed child book up for res...
4  31967    3rd #bihday to my amazing, hilarious #nephew...

In [4]:
train_y = train['label']
train.drop(['label'], axis = 1, inplace = True)

In [5]:
# calculating number of stopwords
import nltk
# nltk.download('stopwords')
from nltk.corpus import stopwords
stop = stopwords.words('english')
train['stopwords'] = train['tweet'].apply(lambda x: len([x for x in x.split() if x in stop]))
test['stopwords'] = test['tweet'].apply(lambda x: len([x for x in x.split() if x in stop]))
test.head()

      id                                              tweet  stopwords
0  31963  #studiolife #aislife #requires #passion #dedic...          1
1  31964   @user #white #supremacists want everyone to s...          4
2  31965  safe ways to heal your #acne!!    #altwaystohe...          2
3  31966  is the hp and the cursed child book up for res...          8
4  31967    3rd #bihday to my amazing, hilarious #nephew...          4

In [6]:
# calculaing number of numerics
train['numerics'] = train['tweet'].apply(lambda x: len([x for x in x.split() if x.isdigit()]))
test['numerics'] = test['tweet'].apply(lambda x: len([x for x in x.split() if x.isdigit()]))
test.head()

,id,tweet,stopwords,numerics
0,31963,#studiolife #aislife #requires #passion #dedic...,1,0
1,31964,@user #white #supremacists want everyone to s...,4,0
2,31965,safe ways to heal your #acne!! #altwaystohe...,2,0
3,31966,is the hp and the cursed child book up for res...,8,0
4,31967,"3rd #bihday to my amazing, hilarious #nephew...",4,0

In [7]:
# calculating number of uppercases
train['upper'] = train['tweet'].apply(lambda x: len([x for x in x.split() if x.isupper()]))
test['upper'] = test['tweet'].apply(lambda x: len([x for x in x.split() if x.isupper()]))
test.head()

,id,tweet,stopwords,numerics,upper
0,31963,#studiolife #aislife #requires #passion #dedic...,1,0,0
1,31964,@user #white #supremacists want everyone to s...,4,0,0
2,31965,safe ways to heal your #acne!! #altwaystohe...,2,0,0
3,31966,is the hp and the cursed child book up for res...,8,0,0
4,31967,"3rd #bihday to my amazing, hilarious #nephew...",4,0,0

In [8]:
train['tweet'] = train['tweet'].apply(lambda x: " ".join(x.lower() for x in x.split()))
test['tweet'] = test['tweet'].apply(lambda x: " ".join(x.lower() for x in x.split()))
test.head()

,id,tweet,stopwords,numerics,upper
0,31963,#studiolife #aislife #requires #passion #dedic...,1,0,0
1,31964,@user #white #supremacists want everyone to se...,4,0,0
2,31965,safe ways to heal your #acne!! #altwaystoheal ...,2,0,0
3,31966,is the hp and the cursed child book up for res...,8,0,0
4,31967,"3rd #bihday to my amazing, hilarious #nephew e...",4,0,0

In [9]:
# Removal of stopwords
from nltk.corpus import stopwords
stop = stopwords.words('english')
train['noise1'] = train['tweet'].apply(lambda x: " ".join(x for x in x.split() if x not in stop))
test['noise1'] = test['tweet'].apply(lambda x: " ".join(x for x in x.split() if x not in stop))
test.head()

,id,tweet,stopwords,numerics,upper,noise1
0,31963,#studiolife #aislife #requires #passion #dedic...,1,0,0,#studiolife #aislife #requires #passion #dedic...
1,31964,@user #white #supremacists want everyone to se...,4,0,0,@user #white #supremacists want everyone see n...
2,31965,safe ways to heal your #acne!! #altwaystoheal ...,2,0,0,safe ways heal #acne!! #altwaystoheal #healthy...
3,31966,is the hp and the cursed child book up for res...,8,0,0,hp cursed child book reservations already? yes...
4,31967,"3rd #bihday to my amazing, hilarious #nephew e...",4,0,0,"3rd #bihday amazing, hilarious #nephew eli ahm..."

In [10]:
import re

regex_pattern = "@[\w]*"
def calc_user(cols):
    input_text = str(cols[0])
    urls = re.finditer(regex_pattern, input_text)
    j = 0
    for i in urls: 
        input_text = re.sub(i.group().strip(), '', input_text)
#         print(i.group())
        j = j+1
    return j
def remove_at(cols):
    input_text = str(cols[0])
    urls = re.finditer(regex_pattern, input_text)
    j = 0
    for i in urls: 
        input_text = re.sub(i.group().strip(), '', input_text)
#         print(i.group())
        j = j+1
    return input_text
# remove_regex("remove this @hashtag @from analytics vidhya")
train['user_mention'] = train[['noise1']].apply(calc_user, axis = 1)
test['user_mention'] = test[['noise1']].apply(calc_user, axis = 1)
train['noise1'] = train[['noise1']].apply(remove_at, axis = 1)
test['noise1'] = test[['noise1']].apply(remove_at, axis = 1)
train.head()

,id,tweet,stopwords,numerics,upper,noise1,user_mention
0,1,@user when a father is dysfunctional and is so...,10,0,0,father dysfunctional selfish drags kids dysfu...,1
1,2,@user @user thanks for #lyft credit i can't us...,5,0,0,thanks #lyft credit can't use cause offer wh...,2
2,3,bihday your majesty,1,0,0,bihday majesty,0
3,4,#model i love u take with u all the time in ur...,5,0,0,#model love u take u time urð±!!! ððð...,0
4,5,factsguide: society now #motivation,1,0,0,factsguide: society #motivation,0

In [11]:
regex_pattern2 = "#[\w]*"

def compute_hash(cols):
    input_text = str(cols[0])
    
    urls = re.finditer(regex_pattern2, input_text)
    hashtags = [i.group() for i in urls]
    
    hashtags = [j[1:] for j in hashtags]
    return ", ".join(hashtags)
# compute_hash("remove this #hashtag #from analytics vidhya")

def remove_hash(cols):
    input_text = str(cols[0])
    
    urls = re.finditer(regex_pattern2, input_text)
    for i in urls: 
        input_text = re.sub(i.group().strip(), '', input_text)
    return input_text
train['hashtags'] = train[['noise1']].apply(compute_hash, axis = 1)
test['hashtags'] = test[['noise1']].apply(compute_hash, axis = 1)
train['noise1'] = train[['noise1']].apply(remove_hash, axis = 1)
test['noise1'] = test[['noise1']].apply(remove_hash, axis = 1)
test.head()

,id,tweet,stopwords,numerics,upper,noise1,user_mention,hashtags
0,31963,#studiolife #aislife #requires #passion #dedic...,1,0,0,find ¦,0,"studiolife, aislife, requires, passion, dedica..."
1,31964,@user #white #supremacists want everyone to se...,4,0,0,want everyone see new â  â hereâs,1,"white, supremacists, birdsâ, movie"
2,31965,safe ways to heal your #acne!! #altwaystoheal ...,2,0,0,safe ways heal !! !!,0,"acne, altwaystoheal, healthy, healing"
3,31966,is the hp and the cursed child book up for res...,8,0,0,hp cursed child book reservations already? yes...,0,"harrypotter, pottermore, favorite"
4,31967,"3rd #bihday to my amazing, hilarious #nephew e...",4,0,0,"3rd amazing, hilarious eli ahmir! uncle dave...",0,"bihday, nephew"

In [12]:
# object Standardisation
lookup_dict = {'rt':'Retweet', 'dm':'direct message', "awsm" : "awesome", "luv" :"love",
               "u" :"you", "ur": "your", "ty": "thankyou" }
def _lookup_words(cols):
    input_text = str(cols[0])
    words = input_text.split() 
    new_words = [] 
    for word in words:
        if word.lower() in lookup_dict:
            word = lookup_dict[word.lower()]
        new_words.append(word) 
    new_text = " ".join(new_words) 
    return new_text
train['noise1'] = train[['noise1']].apply(_lookup_words, axis = 1)
test['noise1'] = test[['noise1']].apply(_lookup_words, axis = 1)
train['hashtags'] = train[['hashtags']].apply(_lookup_words, axis = 1)
test['hashtags'] = test[['hashtags']].apply(_lookup_words, axis = 1)
train.head()

,id,tweet,stopwords,numerics,upper,noise1,user_mention,hashtags
0,1,@user when a father is dysfunctional and is so...,10,0,0,father dysfunctional selfish drags kids dysfun...,1,run
1,2,@user @user thanks for #lyft credit i can't us...,5,0,0,thanks credit can't use cause offer wheelchair...,2,"lyft, disapointed, getthanked"
2,3,bihday your majesty,1,0,0,bihday majesty,0,
3,4,#model i love u take with u all the time in ur...,5,0,0,love you take you time urð±!!! ðððð...,0,model
4,5,factsguide: society now #motivation,1,0,0,factsguide: society,0,motivation

In [13]:
import gensim
from gensim.utils import lemmatize

def lemmatize_genism(cols):
    input_text = cols[0]
    output = [wd.decode('utf-8').split('/')[0] for wd in lemmatize(input_text)]
    output_text = " ".join(output)
    return output_text
train['genism_lemm'] = train[['noise1']].apply(lemmatize_genism, axis = 1)
train['hash2'] = train[['hashtags']].apply(lemmatize_genism, axis = 1)
test['genism_lemm'] = test[['noise1']].apply(lemmatize_genism, axis = 1)
test['hash2'] = test[['hashtags']].apply(lemmatize_genism, axis = 1)
train.head()

,id,tweet,stopwords,numerics,upper,noise1,user_mention,hashtags,genism_lemm,hash2
0,1,@user when a father is dysfunctional and is so...,10,0,0,father dysfunctional selfish drags kids dysfun...,1,run,father dysfunctional selfish draghunt kid dysf...,run
1,2,@user @user thanks for #lyft credit i can't us...,5,0,0,thanks credit can't use cause offer wheelchair...,2,"lyft, disapointed, getthanked",thank credit use cause offer wheelchair van pdx,lyft disapoint getthanked
2,3,bihday your majesty,1,0,0,bihday majesty,0,,bihday majesty,
3,4,#model i love u take with u all the time in ur...,5,0,0,love you take you time urð±!!! ðððð...,0,model,love take time urð,model
4,5,factsguide: society now #motivation,1,0,0,factsguide: society,0,motivation,factsguide society,motivation

In [14]:
from textblob import TextBlob
train['sentiment'] = train['genism_lemm'].apply(lambda x: TextBlob(x).sentiment[0])
test['sentiment'] = test['genism_lemm'].apply(lambda x: TextBlob(x).sentiment[0])
train.head()

,id,tweet,stopwords,numerics,upper,noise1,user_mention,hashtags,genism_lemm,hash2,sentiment
0,1,@user when a father is dysfunctional and is so...,10,0,0,father dysfunctional selfish drags kids dysfun...,1,run,father dysfunctional selfish draghunt kid dysf...,run,-0.5
1,2,@user @user thanks for #lyft credit i can't us...,5,0,0,thanks credit can't use cause offer wheelchair...,2,"lyft, disapointed, getthanked",thank credit use cause offer wheelchair van pdx,lyft disapoint getthanked,0.0
2,3,bihday your majesty,1,0,0,bihday majesty,0,,bihday majesty,,0.0
3,4,#model i love u take with u all the time in ur...,5,0,0,love you take you time urð±!!! ðððð...,0,model,love take time urð,model,0.5
4,5,factsguide: society now #motivation,1,0,0,factsguide: society,0,motivation,factsguide society,motivation,0.0

In [15]:
test.head()

,id,tweet,stopwords,numerics,upper,noise1,user_mention,hashtags,genism_lemm,hash2,sentiment
0,31963,#studiolife #aislife #requires #passion #dedic...,1,0,0,find ¦,0,"studiolife, aislife, requires, passion, dedica...",find,studiolife aislife require passion dedication ...,0.000000
1,31964,@user #white #supremacists want everyone to se...,4,0,0,want everyone see new â  â hereâs,1,"white, supremacists, birdsâ, movie",want everyone see new hereâ,white supremacist birdsâ movie,0.136364
2,31965,safe ways to heal your #acne!! #altwaystoheal ...,2,0,0,safe ways heal !! !!,0,"acne, altwaystoheal, healthy, healing",safe way heal,acne altwaystoheal healthy healing,0.500000
3,31966,is the hp and the cursed child book up for res...,8,0,0,hp cursed child book reservations already? yes...,0,"harrypotter, pottermore, favorite",hp curse child book reservation already yes no,harrypotter pottermore favorite,0.000000
4,31967,"3rd #bihday to my amazing, hilarious #nephew e...",4,0,0,"3rd amazing, hilarious eli ahmir! uncle dave l...",0,"bihday, nephew",rd amazing hilarious eli ahmir uncle dave love...,bihday nephew,0.533333

In [16]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer(max_features=800, lowercase=True, analyzer='word',
                         stop_words= 'english',ngram_range=(1,1))
train_tfidf_vect = tfidf.fit_transform(train['genism_lemm'])
test_tfidf_vect = tfidf.transform(test['genism_lemm'])

In [17]:
tfidf2 = TfidfVectorizer(max_features = 400, lowercase = True, analyzer='word',
                        stop_words = 'english', ngram_range = (1,1))
train_hash_vect = tfidf2.fit_transform(train['hash2'])
test_hash_vect = tfidf2.transform(test['hash2'])

In [18]:
# train_tfidf_vect.shape
df = pd.DataFrame(train_tfidf_vect.toarray())
df_ = pd.DataFrame(test_tfidf_vect.toarray())
df2 = pd.DataFrame(train_hash_vect.toarray())
df2_ = pd.DataFrame(test_hash_vect.toarray())

In [19]:
# Creating Bag of Words
import sklearn.feature_extraction.text
from sklearn.feature_extraction.text import CountVectorizer
bow = CountVectorizer(max_features=800, lowercase=True, ngram_range=(1,1),analyzer = "word")
train_bow = bow.fit_transform(train['genism_lemm'])
test_bow = bow.transform(test['genism_lemm'])

In [20]:
bow2 = CountVectorizer(max_features = 400, lowercase = True, ngram_range = (1,1), analyzer = "word")
train_hash_bow = bow2.fit_transform(train['hash2'])
test_hash_bow = bow2.transform(test['hash2'])

In [21]:
df1 = pd.DataFrame(train_bow.toarray())
df1_ = pd.DataFrame(test_bow.toarray())
df3 = pd.DataFrame(train_hash_bow.toarray())
df3_ = pd.DataFrame(test_hash_bow.toarray())

In [22]:
from sklearn.decomposition import PCA
import numpy as np
pca1 = PCA(n_components = 100)
df_all = np.concatenate([df.values, df_.values])
pca1.fit(df_all)
df = pca1.transform(df.values)
df_ = pca1.transform(df_.values)
# converting array to again dataframe
df = pd.DataFrame(df)
df_ = pd.DataFrame(df_)

In [23]:
from sklearn.decomposition import PCA
pca2 = PCA(n_components = 100)
df1_all = np.concatenate([df1.values, df1_.values])
pca2.fit(df1_all)
df1 = pca2.transform(df1.values)
df1_ = pca2.transform(df1_.values)
# ////
df1 = pd.DataFrame(df1)
df1_ = pd.DataFrame(df1_)

In [24]:
pca3 = PCA(n_components = 70)
df2_all = np.concatenate([df2.values, df2_.values])
pca3.fit(df2_all)
df2 = pca3.transform(df2.values)
df2_ = pca3.transform(df2_.values)
# //
df2 = pd.DataFrame(df2)
df2_ = pd.DataFrame(df2_)

In [25]:
pca4 = PCA(n_components = 70)
df3_all = np.concatenate([df3.values, df3_.values])
pca4.fit(df3_all)
df3 = pca4.transform(df3.values)
df3_ = pca4.transform(df3_.values)
# //
df3 = pd.DataFrame(df3)
df3_ = pd.DataFrame(df3_)

In [26]:
df3

,0,1,2,3,4,5,6,7,8,9,...,60,61,62,63,64,65,66,67,68,69
0,-0.051178,-0.040536,-0.022242,-0.020139,-0.011913,-0.006795,-0.002466,-0.021007,-0.006004,-0.015851,...,-0.060516,0.056593,-0.033898,0.014292,0.042019,0.053804,-0.028318,-0.130021,0.047160,0.000264
1,-0.052728,-0.040017,-0.021350,-0.022175,-0.011632,-0.007430,-0.003330,-0.023527,-0.004953,-0.019069,...,-0.003174,-0.001197,0.002042,0.000446,-0.001445,-0.001088,0.000287,0.001595,0.000112,-0.000503
2,-0.052728,-0.040017,-0.021350,-0.022175,-0.011632,-0.007430,-0.003330,-0.023527,-0.004953,-0.019069,...,-0.003174,-0.001197,0.002042,0.000446,-0.001445,-0.001088,0.000287,0.001595,0.000112,-0.000503
3,-0.056969,-0.052800,-0.031507,-0.037342,-0.012443,-0.012855,-0.008745,-0.038795,-0.046262,-0.100157,...,0.004689,-0.000331,-0.005026,-0.000186,0.002151,-0.002372,-0.000285,0.000318,-0.005283,0.001909
4,-0.045540,-0.037684,-0.024053,-0.015587,-0.025016,-0.007642,-0.003377,-0.020699,-0.028745,-0.013094,...,-0.050825,-0.193530,-0.009486,-0.053573,-0.032624,0.017314,0.046966,0.068540,0.103433,-0.011487
5,-0.052728,-0.040017,-0.021350,-0.022175,-0.011632,-0.007430,-0.003330,-0.023527,-0.004953,-0.019069,...,-0.003174,-0.001197,0.002042,0.000446,-0.001445,-0.001088,0.000287,0.001595,0.000112,-0.000503
6,-0.052728,-0.040017,-0.021350,-0.022175,-0.011632,-0.007430,-0.003330,-0.023527,-0.004953,-0.019069,...,-0.003174,-0.001197,0.002042,0.000446,-0.001445,-0.001088,0.000287,0.001595,0.000112,-0.000503
7,0.005660,-0.040116,-0.026644,-0.048612,0.139433,-0.011627,-0.010017,0.196463,-0.024234,0.009554,...,0.038497,0.041181,-0.014053,-0.011359,0.084588,-0.036108,-0.063764,-0.049344,-0.007032,-0.046640
8,-0.052728,-0.040017,-0.021350,-0.022175,-0.011632,-0.007430,-0.003330,-0.023527,-0.004953,-0.019069,...,-0.003174,-0.001197,0.002042,0.000446,-0.001445,-0.001088,0.000287,0.001595,0.000112,-0.000503
9,-0.052728,-0.040017,-0.021350,-0.022175,-0.011632,-0.007430,-0.003330,-0.023527,-0.004953,-0.019069,...,-0.003174,-0.001197,0.002042,0.000446,-0.001445,-0.001088,0.000287,0.001595,0.000112,-0.000503
10,-0.141547,-0.209772,1.956225,0.079320,0.025444,0.010605,0.004099,0.024973,0.009319,0.009289,...,-0.002950,0.001882,0.001042,-0.000038,-0.001120,0.002773,0.003273,-0.001058,-0.000461,0.002177
11,0.857644,0.111069,0.035325,0.004066,-0.316868,0.045379,-0.009588,-0.029842,0.031520,-0.166606,...,-0.040733,-0.001020,-0.011500,0.032207,-0.029667,-0.020823,0.002361,-0.007816,-0.032228,-0.007374
12,-0.041937,-0.046498,-0.029616,-0.038018,-0.030646,-0.011575,-0.006899,0.012344,0.377453,0.326228,...,0.015912,-0.003105,-0.073701,-0.014121,0.013378,-0.022331,0.070293,-0.002184,-0.011876,0.000078
13,-0.052728,-0.040017,-0.021350,-0.022175,-0.011632,-0.007430,-0.003330,-0.023527,-0.004953,-0.019069,...,-0.003174,-0.001197,0.002042,0.000446,-0.001445,-0.001088,0.000287,0.001595,0.000112,-0.000503
14,-0.053620,-0.040777,-0.015138,-0.022354,-0.011792,-0.007611,-0.003282,-0.023800,-0.005036,-0.019712,...,0.003590,0.000251,0.003458,0.005044,-0.001765,0.002031,0.001245,0.003212,-0.007011,0.004078
15,-0.052728,-0.040017,-0.021350,-0.022175,-0.011632,-0.007430,-0.003330,-0.023527,-0.004953,-0.019069,...,-0.003174,-0.001197,0.002042,0.000446,-0.001445,-0.001088,0.000287,0.001595,0.000112,-0.000503
16,-0.239777,1.043975,0.055391,0.016888,-0.011882,-0.014828,0.875479,0.042893,0.014161,-0.001252,...,0.001815,-0.004007,-0.001127,-0.002001,0.000946,-0.000484,-0.000098,0.000789,0.001789,-0.001792
17,-0.052728,-0.040017,-0.021350,-0.022175,-0.011632,-0.007430,-0.003330,-0.023527,-0.004953,-0.019069,...,-0.003174,-0.001197,0.002042,0.000446,-0.001445,-0.001088,0.000287,0.001595,0.000112,-0.000503
18,-0.046104,-0.044079,-0.024103,-0.028914,-0.009180,-0.009831,-0.005710,0.012518,-0.032644,0.024935,...,0.005041,0.004828,0.002712,0.008292,-0.008454,-0.006765,0.000869,-0.002196,-0.001250,-0.022314
19,-0.052728,-0.040017,-0.021350,-0.022175,-0.011632,-0.007430,-0.003330,-0.023527,-0.004953,-0.019069,...,-0.003174,-0.001197,0.002042,0.000446,-0.001445,-0.001088,0.000287,0.001595,0.000112,-0.000503
20,-0.057211,-0.045083,-0.019221,-0.026265,-0.015083,-0.009468,-0.004466,-0.028325,-0.010014,-0.025604,...,0.002695,-0.000811,-0.005055,-0.005401,0.003359,-0.000316,-0.001316,0.001135,-0.005137,-0.001251
21,-0.031108,-0.043176,-0.025114,-0.032813,0.013849,-0.012512,-0.006455,0.027395,-0.012387,-0.021162,...,0.071548,0.066430,-0.346875,0.296470,0.326650,0.163064,0.097721,0.347845,-0.152378,-0.134771
22,-0.034473,-0.045226,-0.027277,-0.028567,-0.012193,-0.008252,-0.007874,0.048720,0.000249,0.010954,...,-0.013492,-0.006455,0.037611,0.004325,-0.008226,0.028456,0.026690,0.026075,-0.008658,0.003332
23,-0.052728,-0.040017,-0.021350,-0.022175,-0.011632,-0.007430,-0.003330,-0.023527,-0.004953,-0.019069,...,-0.003174,-0.001197,0.002042,0.000446,-0.001445,-0.001088,0.000287,0.001595,0.000112,-0.000503
24,-0.053635,-0.045312,-0.025882,-0.020150,-0.011171,-0.009962,-0.004725,-0.018960,-0.008238,-0.019849,...,0.189218,-0.246147,-0.194550,-0.029572,0.102828,-0.071812,-0.115560,-0.026932,-0.047310,0.051480
25,0.860393,0.118629,0.039191,0.010954,-0.303220,0.048635,-0.008057,-0.015872,0.034637,-0.144801,...,-0.030010,-0.015699,-0.003414,0.009005,-0.001751,0.001277,-0.004982,-0.004691,-0.001015,-0.001096
26,0.015070,-0.037245,-0.026543,-0.042230,0.044259,-0.019352,-0.007143,0.155176,-0.382111,0.622679,...,0.007852,-0.004349,-0.002311,0.026130,-0.000845,0.028448,-0.000913,0.034842,0.031864,-0.000958
27,-0.052728,-0.040017,-0.021350,-0.022175,-0.011632,-0.007430,-0.003330,-0.023527,-0.004953,-0.019069,...,-0.003174,-0.001197,0.002042,0.000446,-0.001445,-0.001088,0.000287,0.001595,0.000112,-0.000503
28,-0.052728,-0.040017,-0.021350,-0.022175,-0.011632,-0.007430,-0.003330,-0.023527,-0.004953,-0.019069,...,-0.003174,-0.001197,0.002042,0.000446,-0.001445,-0.001088,0.000287,0.001595,0.000112,-0.000503
29,-0.056793,-0.049567,-0.026669,-0.030832,-0.025651,-0.011536,-0.005345,-0.040549,-0.007299,-0.041071,...,0.156585,-0.092175,-0.085323,-0.013971,0.094302,0.546007,-0.012063,-0.389274,-0.059132,0.253536
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31932,-0.052728,-0.040017,-0.021350,-0.022175,-0.011632,-0.007430,-0.003330,-0.023527,-0.004953,-0.019069,...,-0.003174,-0.001197,0.002042,0.000446,-0.001445,-0.001088,0.000287,0.001595,0.000112,-0.000503
31933,-0.052728,-0.040017,-0.021350,-0.022175,-0.011632,-0.007430,-0.003330,-0.023527,-0.004953,-0.019069,...,-0.003174,-0.001197,0.002042,0.000446,-0.001445,-0.001088,0.000287,0.001595,0.000112,-0.000503
31934,-0.052728,-0.040017,-0.021350,-0.022175,-0.011632,-0.007430,-0.003330,-0.023527,-0.004953,-0.019069,...,-0.003174,-0.001197,0.002042,0.000446,-0.001445,-0.001088,0.000287,0.001595,0.000112,-0.000503
31935,-0.052728,-0.040017,-0.021350,-0.022175,-0.011632,-0.007430,-0.003330,-0.023527,-0.004953,-0.019069,...,-0.003174,-0.001197,0.002042,0.000446,-0.001445,-0.001088,0.000287,0.001595,0.000112,-0.000503
31936,-0.052728,-0.040017,-0.021350,-0.022175,-0.011632,-0.007430,-0.003330,-0.023527,-0.004953,-0.019069,...,-0.003174,-0.001197,0.002042,0.000446,-0.001445,-0.001088,0.000287,0.001595,0.000112,-0.000503
31937,-0.052728,-0.040017,-0.021350,-0.022175,-0.011632,-0.007430,-0.003330,-0.023527,-0.004953,-0.019069,...,-0.003174,-0.001197,0.002042,0.000446,-0.001445,-0.001088,0.000287,0.001595,0.000112,-0.000503
31938,-0.052728,-0.040017,-0.021350,-0.022175,-0.011632,-0.007430,-0.003330,-0.023527,-0.004953,-0.019069,...,-0.003174,-0.001197,0.002042,0.000446,-0.001445,-0.001088,0.000287,0.001595,0.000112,-0.000503
31939,-0.046104,-0.044079,-0.024103,-0.028914,-0.009180,-0.009831,-0.005710,0.012518,-0.032644,0.024935,...,0.005041,0.004828,0.002712,0.008292,-0.008454,-0.006765,0.000869,-0.002196,-0.001250,-0.022314
31940,-0.052728,-0.040017,-0.021350,-0.022175,-0.011632,-0.007430,-0.003330,-0.023527,-0.004953,-0.019069,...,-0.003174,-0.001197,0.002042,0.000446,-0.001445,-0.001088,0.000287,0.001595,0.000112,-0.000503
31941,0.860393,0.118629,0.039191,0.010954,-0.303220,0.048635,-0.008057,-0.015872,0.034637,-0.144801,...,-0.030010,-0.015699,-0.003414,0.009005,-0.001751,0.001277,-0.004982,-0.004691,-0.001015,-0.001096
31942,-0.051782,-0.040393,-0.022172,-0.023542,-0.011022,-0.006695,-0.003124,-0.020845,-0.010411,-0.012363,...,-0.007936,-0.012121,-0.015567,-0.008847,-0.002700,-0.004812,0.004895,0.000980,-0.001231,0.048815
31943,-0.011078,-0.047306,-0.029513,-0.049285,0.100790,-0.034867,-0.003896,-0.095552,-0.075130,-0.047041,...,0.058732,-0.014635,-0.035297,0.048411,-0.050078,0.039154,-0.132066,0.056975,-0.031798,0.012661
31944,-0.052728,-0.040017,-0.021350,-0.022175,-0.011632,-0.007430,-0.003330,-0.023527,-0.004953,-0.019069,...,-0.003174,-0.001197,0.002042,0.000446,-0.001445,-0.001088,0.000287,0.001595,0.000112,-0.000503
31945,0.039626,-0.060352,-0.052415,-0.106326,0.488765,0.264596,-0.020164,0.736259,0.512485,0.175914,...,0.010720,0.027659,-0.101004,0.016813,-0.267610,0.142414,-0.012322,0.118647,0.042655,-0.111420
31946,-0.052728,-0.040017,-0.021350,-0.022175,-0.011632,-0.007430,-0.003330,-0.023527,-0.004953,-0.019069,...,-0.003174,-0.001197,0.002042,0.000446,-0.001445,-0.001088,0.000287,0.001595,0.000112,-0.000503
31947,-0.052728,-0.040017,-0.021350,-0.022175,-0.011632,-0.007430,-0.003330,-0.023527,-0.004953,-0.019069,...,-0.003174,-0.001197,0.002042,0.000446,-0.001445,-0.001088,0.000287,0.001595,0.000112,-0.000503
31948,-0.052728,-0.040017,-0.021350,-0.022175,-0.011632,-0.007430,-0.003330,-0.023527,-0.004953,-0.019069,...,-0.003174,-0.001197,0.002042,0.000446,-0.001445,-0.001088,0.000287,0.001595,0.000112,-0.000503
31949,-0.032119,-0.046660,-0.029678,0.002994,-0.029246,-0.008036,-0.010504,0.040949,-0.080393,0.055071,...,0.010592,0.037204,-0.016670,-0.020869,0.010769,-0.029583,0.010121,0.003419,0.017765,0.003164
31950,-0.049806,-0.040827,-0.022238,-0.024682,0.002814,-0.009919,-0.003511,-0.018601,-0.004605,-0.022521,...,-0.018759,0.047380,-0.050478,0.017554,0.119066,0.014399,-0.037066,0.039366,0.004772,-0.062224
31951,-0.053181,-0.041205,-0.022218,-0.022969,-0.012072,-0.007471,-0.003573,-0.025324,-0.006610,-0.020293,...,0.000932,-0.001222,-0.016393,0.014559,0.011550,-0.010581,0.001151,0.035471,0.006550,-0.018148
31952,-0.052728,-0.040017,-0.021350,-0.022175,-0.011632,-0.007430,-0.003330,-0.023527,-0.004953,-0.019069,...,-0.003174,-0.001197,0.002042,0.000446,-0.001445,-0.001088,0.000287,0.001595,0.000112,-0.000503
31953,0.009490,-0.038193,-0.025192,-0.048732,0.147882,-0.012209,-0.008712,0.187592,-0.031040,0.011238,...,-0.039410,0.014339,0.022150,-0.101417,0.055500,0.003921,0.047823,0.055822,-0.019510,-0.033594
31954,-0.045926,-0.042548,-0.024001,-0.028309,0.001651,-0.007475,-0.005719,0.018063,0.004445,-0.024188,...,0.000823,0.001408,0.031628,0.011229,-0.013885,0.017940,-0.012991,-0.013344,-0.034403,0.043684
31955,-0.000941,-0.047298,-0.034487,-0.058621,0.235623,-0.009937,-0.017529,0.418337,0.074015,-0.102582,...,0.000241,-0.009062,0.031525,0.027989,0.003450,0.028657,-0.009710,-0.018822,-0.045100,0.038403
31956,-0.052728,-0.040017,-0.021350,-0.022175,-0.011632,-0.007430,-0.003330,-0.023527,-0.004953,-0.019069,...,-0.003174,-0.001197,0.002042,0.000446,-0.001445,-0.001088,0.000287,0.001595,0.000112,-0.000503
31957,-0.052728,-0.040017,-0.021350,-0.022175,-0.011632,-0.007430,-0.003330,-0.023527,-0.004953,-0.019069,...,-0.003174,-0.001197,0.002042,0.000446,-0.001445,-0.001088,0.000287,0.001595,0.000112,-0.000503
31958,-0.052728,-0.040017,-0.021350,-0.022175,-0.011632,-0.007430,-0.003330,-0.023527,-0.004953,-0.019069,...,-0.003174,-0.001197,0.002042,0.000446,-0.001445,-0.001088,0.000287,0.001595,0.000112,-0.000503
31959,-0.052728,-0.040017,-0.021350,-0.022175,-0.011632,-0.007430,-0.003330,-0.023527,-0.004953,-0.019069,...,-0.003174,-0.001197,0.002042,0.000446,-0.001445,-0.001088,0.000287,0.001595,0.000112,-0.000503
31960,-0.054455,-0.042300,-0.022945,-0.024413,-0.013323,-0.008463,-0.003826,-0.027307,-0.007268,-0.022261,...,-0.064712,0.144089,0.018627,0.015582,0.012467,-0.086033,0.010238,-0.120231,-0.161336,0.011161
31961,-0.052728,-0.040017,-0.021350,-0.022175,-0.011632,-0.007430,-0.003330,-0.023527,-0.004953,-0.019069,...,-0.003174,-0.001197,0.002042,0.000446,-0.001445,-0.001088,0.000287,0.001595,0.000112,-0.000503

In [27]:
train2 = pd.merge(train, df, left_index = True, right_index = True)
test2 = pd.merge(test, df_, left_index = True, right_index = True)
train2 = pd.merge(train2, df2, left_index = True, right_index = True)
test2 = pd.merge(test2, df2_, left_index = True, right_index = True)

In [28]:
train3 = pd.merge(train2, df1, left_index = True, right_index = True)
test3 = pd.merge(test2, df1_, left_index = True, right_index = True)
train3 = pd.merge(train3, df3, left_index = True, right_index = True)
test3 = pd.merge(test3, df3_, left_index = True, right_index = True)

In [29]:
train3.head()

,id,tweet,stopwords,numerics,upper,noise1,user_mention,hashtags,genism_lemm,hash2,...,60_y,61_y,62_y,63_y,64_y,65_y,66_y,67_y,68_y,69_y
0,1,@user when a father is dysfunctional and is so...,10,0,0,father dysfunctional selfish drags kids dysfun...,1,run,father dysfunctional selfish draghunt kid dysf...,run,...,-0.060516,0.056593,-0.033898,0.014292,0.042019,0.053804,-0.028318,-0.130021,0.047160,0.000264
1,2,@user @user thanks for #lyft credit i can't us...,5,0,0,thanks credit can't use cause offer wheelchair...,2,"lyft, disapointed, getthanked",thank credit use cause offer wheelchair van pdx,lyft disapoint getthanked,...,-0.003174,-0.001197,0.002042,0.000446,-0.001445,-0.001088,0.000287,0.001595,0.000112,-0.000503
2,3,bihday your majesty,1,0,0,bihday majesty,0,,bihday majesty,,...,-0.003174,-0.001197,0.002042,0.000446,-0.001445,-0.001088,0.000287,0.001595,0.000112,-0.000503
3,4,#model i love u take with u all the time in ur...,5,0,0,love you take you time urð±!!! ðððð...,0,model,love take time urð,model,...,0.004689,-0.000331,-0.005026,-0.000186,0.002151,-0.002372,-0.000285,0.000318,-0.005283,0.001909
4,5,factsguide: society now #motivation,1,0,0,factsguide: society,0,motivation,factsguide society,motivation,...,-0.050825,-0.193530,-0.009486,-0.053573,-0.032624,0.017314,0.046966,0.068540,0.103433,-0.011487

In [30]:
test3.head()

,id,tweet,stopwords,numerics,upper,noise1,user_mention,hashtags,genism_lemm,hash2,...,60_y,61_y,62_y,63_y,64_y,65_y,66_y,67_y,68_y,69_y
0,31963,#studiolife #aislife #requires #passion #dedic...,1,0,0,find ¦,0,"studiolife, aislife, requires, passion, dedica...",find,studiolife aislife require passion dedication ...,...,-0.003174,-0.001197,0.002042,0.000446,-0.001445,-0.001088,0.000287,0.001595,0.000112,-0.000503
1,31964,@user #white #supremacists want everyone to se...,4,0,0,want everyone see new â  â hereâs,1,"white, supremacists, birdsâ, movie",want everyone see new hereâ,white supremacist birdsâ movie,...,0.004156,0.007012,0.014628,-0.009585,-0.005880,-0.000718,0.018018,0.010808,0.016781,-0.007678
2,31965,safe ways to heal your #acne!! #altwaystoheal ...,2,0,0,safe ways heal !! !!,0,"acne, altwaystoheal, healthy, healing",safe way heal,acne altwaystoheal healthy healing,...,0.021169,-0.106529,-0.009217,-0.012652,0.037130,0.027182,-0.029810,0.001530,-0.005934,-0.066898
3,31966,is the hp and the cursed child book up for res...,8,0,0,hp cursed child book reservations already? yes...,0,"harrypotter, pottermore, favorite",hp curse child book reservation already yes no,harrypotter pottermore favorite,...,-0.003174,-0.001197,0.002042,0.000446,-0.001445,-0.001088,0.000287,0.001595,0.000112,-0.000503
4,31967,"3rd #bihday to my amazing, hilarious #nephew e...",4,0,0,"3rd amazing, hilarious eli ahmir! uncle dave l...",0,"bihday, nephew",rd amazing hilarious eli ahmir uncle dave love...,bihday nephew,...,0.008018,-0.007356,0.016573,0.002682,0.000631,0.008202,0.015085,0.001175,-0.003819,-0.007650

In [31]:
train3['word_count'] = train3['genism_lemm'].apply(lambda x: len(str(x).split(" ")))
test3['word_count'] = test3['genism_lemm'].apply(lambda x: len(str(x).split(" ")))

train3['char_count'] = train3['genism_lemm'].str.len()
test3['char_count'] = test3['genism_lemm'].str.len()

train3['hastags_count'] = train3['tweet'].apply(lambda x: len([x for x in x.split() if x.startswith('#')]))
test3['hastags_count'] = test3['tweet'].apply(lambda x: len([x for x in x.split() if x.startswith('#')]))

In [32]:
train3.shape

(31962, 354)

In [33]:
test3.shape

(17197, 354)

In [34]:
train3.columns

Index(['id', 'tweet', 'stopwords', 'numerics', 'upper', 'noise1',
       'user_mention', 'hashtags', 'genism_lemm', 'hash2',
       ...
       '63_y', '64_y', '65_y', '66_y', '67_y', '68_y', '69_y', 'word_count',
       'char_count', 'hastags_count'],
      dtype='object', length=354)

In [35]:
cols = ['tweet', 'noise1', 'hashtags', 'genism_lemm', 'hash2', 'id']
train3.drop(cols, axis = 1, inplace = True)

In [36]:
test3.drop(cols, axis = 1, inplace = True)

In [37]:
train3.head()

,stopwords,numerics,upper,user_mention,sentiment,0_x,1_x,2_x,3_x,4_x,...,63_y,64_y,65_y,66_y,67_y,68_y,69_y,word_count,char_count,hastags_count
0,10,0,0,1,-0.5,0.152920,0.024042,-0.013365,-0.015425,-0.028913,...,0.014292,0.042019,0.053804,-0.028318,-0.130021,0.047160,0.000264,6,53,1
1,5,0,0,2,0.0,-0.031551,-0.032375,-0.014239,-0.021525,-0.012394,...,0.000446,-0.001445,-0.001088,0.000287,0.001595,0.000112,-0.000503,8,47,3
2,1,0,0,0,0.0,-0.005010,-0.039123,0.174968,-0.049157,-0.119076,...,0.000446,-0.001445,-0.001088,0.000287,0.001595,0.000112,-0.000503,2,14,0
3,5,0,0,0,0.5,-0.239905,0.883869,0.018206,0.018790,0.012645,...,-0.000186,0.002151,-0.002372,-0.000285,0.000318,-0.005283,0.001909,4,18,1
4,1,0,0,0,0.0,-0.027979,-0.026474,-0.011341,-0.020703,-0.012069,...,-0.053573,-0.032624,0.017314,0.046966,0.068540,0.103433,-0.011487,2,18,1

In [38]:
test3.head()

,stopwords,numerics,upper,user_mention,sentiment,0_x,1_x,2_x,3_x,4_x,...,63_y,64_y,65_y,66_y,67_y,68_y,69_y,word_count,char_count,hastags_count
0,1,0,0,0,0.000000,-0.027979,-0.026474,-0.011341,-0.020703,-0.012069,...,0.000446,-0.001445,-0.001088,0.000287,0.001595,0.000112,-0.000503,1,4,7
1,4,0,0,1,0.136364,-0.047460,-0.053651,-0.024738,-0.049453,-0.027440,...,-0.009585,-0.005880,-0.000718,0.018018,0.010808,0.016781,-0.007678,5,27,4
2,2,0,0,0,0.500000,-0.035539,-0.035716,-0.016446,-0.023999,-0.010176,...,-0.012652,0.037130,0.027182,-0.029810,0.001530,-0.005934,-0.066898,3,13,4
3,8,0,0,0,0.000000,-0.032183,-0.031265,-0.016817,-0.016954,-0.016663,...,0.000446,-0.001445,-0.001088,0.000287,0.001595,0.000112,-0.000503,8,46,3
4,4,0,0,0,0.533333,-0.085428,0.256297,0.003360,-0.005465,-0.016893,...,0.002682,0.000631,0.008202,0.015085,0.001175,-0.003819,-0.007650,9,54,2

In [39]:
train3 = pd.merge(train3, train_y, left_index = True, right_index = True)
train3.head()

,stopwords,numerics,upper,user_mention,sentiment,0_x,1_x,2_x,3_x,4_x,...,64_y,65_y,66_y,67_y,68_y,69_y,word_count,char_count,hastags_count,label
0,10,0,0,1,-0.5,0.152920,0.024042,-0.013365,-0.015425,-0.028913,...,0.042019,0.053804,-0.028318,-0.130021,0.047160,0.000264,6,53,1,0
1,5,0,0,2,0.0,-0.031551,-0.032375,-0.014239,-0.021525,-0.012394,...,-0.001445,-0.001088,0.000287,0.001595,0.000112,-0.000503,8,47,3,0
2,1,0,0,0,0.0,-0.005010,-0.039123,0.174968,-0.049157,-0.119076,...,-0.001445,-0.001088,0.000287,0.001595,0.000112,-0.000503,2,14,0,0
3,5,0,0,0,0.5,-0.239905,0.883869,0.018206,0.018790,0.012645,...,0.002151,-0.002372,-0.000285,0.000318,-0.005283,0.001909,4,18,1,0
4,1,0,0,0,0.0,-0.027979,-0.026474,-0.011341,-0.020703,-0.012069,...,-0.032624,0.017314,0.046966,0.068540,0.103433,-0.011487,2,18,1,0

In [40]:
train3.to_csv('train_final_matrix_factorized2.csv', index = False)
test3.to_csv('test_final_matrix_factorized2.csv', index = False)